### ISSUE TITLE
Out of disk space makes database in invalid state

### ISSUE THREAD

**Issue by sondreb** [block-core/blockcore-indexer#141]
Ran out of disk due to rouge process on the infrastructure server and it made multiple chain databases in invalid state.

```dbug: Blockcore.Indexer.Core.Sync.SyncOperations[0]
      Rewinding block 1019518(c44e0701276567d24663fa9355ca3904df85d1e8eca4dc2d83745b7be7ec3581)
fail: Blockcore.Indexer.Core.Sync.SyncTasks.BlockStartup[0]
      TaskStarter-BlockStartup
      MongoDB.Driver.MongoBulkWriteException`1[Blockcore.Indexer.Core.Storage.Mongo.Types.UnspentOutputTable]: A bulk write operation resulted in one or more errors. WriteErrors: [ { Category : "DuplicateKey", Code : 11000, Message : "E11000 duplicate key error collection: BlockchainTSTRAX.UnspentOutput index: Outpoint_1 dup key: { Outpoint: { TransactionId: "64cae697698b11463634c96638ac7d47ca9dc4fd5ca403036ab43c411e213499", OutputIndex: 1 } }" } ].
         at MongoDB.Driver.MongoCollectionImpl`1.BulkWriteAsync(IClientSessionHandle session, IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
         at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
         at Blockcore.Indexer.Core.Storage.Mongo.BlockRewindOperation.MergeRewindInputsToUnspentTransactionsAsync(IMongoDb storage, Int64 blockIndex) in /home/runner/work/blockcore-indexer/blockcore-indexer/src/Blockcore.Indexer.Core/Storage/Mongo/BlockRewindOperation.cs:line 226
         at Blockcore.Indexer.Core.Storage.Mongo.BlockRewindOperation.RewindBlockAsync(IMongoDb storage, UInt32 blockIndex) in /home/runner/work/blockcore-indexer/blockcore-indexer/src/Blockcore.Indexer.Core/Storage/Mongo/BlockRewindOperation.cs:line 91
         at Blockcore.Indexer.Core.Storage.Mongo.MongoData.DeleteBlockAsync(String blockHash) in /home/runner/work/blockcore-indexer/blockcore-indexer/src/Blockcore.Indexer.Core/Storage/Mongo/MongoData.cs:line 963
         at Blockcore.Indexer.Core.Sync.SyncOperations.RewindToLastCompletedBlockAsync() in /home/runner/work/blockcore-indexer/blockcore-indexer/src/Blockcore.Indexer.Core/Sync/SyncOperations.cs:line 144
         at Blockcore.Indexer.Core.Sync.SyncTasks.BlockStartup.OnExecute() in /home/runner/work/blockcore-indexer/blockcore-indexer/src/Blockcore.Indexer.Core/Sync/SyncTasks/BlockStartup.cs:line 117
         at Blockcore.Indexer.Core.Sync.SyncTasks.TaskStarter.<>c__DisplayClass8_0.<<Run>b__0>d.MoveNext() in /home/runner/work/blockcore-indexer/blockcore-indexer/src/Blockcore.Indexer.Core/Sync/SyncTasks/TaskStarter.cs:line 54
fail: Blockcore.Indexer.Core.Sync.SyncServer[0]
      Sync
      MongoDB.Driver.MongoBulkWriteException`1[Blockcore.Indexer.Core.Storage.Mongo.Types.UnspentOutputTable]: A bulk write operation resulted in one or more errors. WriteErrors: [ { Category : "DuplicateKey", Code : 11000, Message : "E11000 duplicate key error collection: BlockchainTSTRAX.UnspentOutput index: Outpoint_1 dup key: { Outpoint: { TransactionId: "64cae697698b11463634c96638ac7d47ca9dc4fd5ca403036ab43c411e213499", OutputIndex: 1 } }" } ].
         at MongoDB.Driver.MongoCollectionImpl`1.BulkWriteAsync(IClientSessionHandle session, IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
         at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
         at Blockcore.Indexer.Core.Storage.Mongo.BlockRewindOperation.MergeRewindInputsToUnspentTransactionsAsync(IMongoDb storage, Int64 blockIndex) in /home/runner/work/blockcore-indexer/blockcore-indexer/src/Blockcore.Indexer.Core/Storage/Mongo/BlockRewindOperation.cs:line 226
         at Blockcore.Indexer.Core.Storage.Mongo.BlockRewindOperation.RewindBlockAsync(IMongoDb storage, UInt32 blockIndex) in /home/runner/work/blockcore-indexer/blockcore-indexer/src/Blockcore.Indexer.Core/Storage/Mongo/BlockRewindOperation.cs:line 91
         at Blockcore.Indexer.Core.Storage.Mongo.MongoData.DeleteBlockAsync(String blockHash) in /home/runner/work/blockcore-indexer/blockcore-indexer/src/Blockcore.Indexer.Core/Storage/Mongo/MongoData.cs:line 963
         at Blockcore.Indexer.Core.Sync.SyncOperations.RewindToLastCompletedBlockAsync() in /home/runner/work/blockcore-indexer/blockcore-indexer/src/Blockcore.Indexer.Core/Sync/SyncOperations.cs:line 144
         at Blockcore.Indexer.Core.Sync.SyncTasks.BlockStartup.OnExecute() in /home/runner/work/blockcore-indexer/blockcore-indexer/src/Blockcore.Indexer.Core/Sync/SyncTasks/BlockStartup.cs:line 117
         at Blockcore.Indexer.Core.Sync.SyncTasks.TaskStarter.<>c__DisplayClass8_0.<<Run>b__0>d.MoveNext() in /home/runner/work/blockcore-indexer/blockcore-indexer/src/Blockcore.Indexer.Core/Sync/SyncTasks/TaskStarter.cs:line 54
w
```

**Comment by DavidGershony** [comment]
This should be fixed as part of issue #160
