### ISSUE TITLE
Rewind bug on cirrus

### ISSUE THREAD

**Issue by dangershony** [block-core/blockcore-indexer#160]
Randomly got this bug so keeping this here to track it

```
crs-indexer | fail: Blockcore.Indexer.Core.Sync.SyncServer[0]
crs-indexer |       Sync
crs-indexer |       MongoDB.Driver.MongoBulkWriteException`1[Blockcore.Indexer.Core.Storage.Mongo.Types.UnspentOutputTable]: A bulk write operation resulted in one or more errors. WriteErrors: [ { Category : "DuplicateKey", Code : 11000, Message : "E11000 duplicate key error collection: BlockchainCRS.UnspentOutput index: Outpoint_1 dup key: { Outpoint: { TransactionId: "8b4e4a65bdaa9c3875835cf3453028aa7debb78a6cb7b360e1dba3ef41e4a939", OutputIndex: 0 } }" } ].
crs-indexer |          at MongoDB.Driver.MongoCollectionImpl`1.BulkWriteAsync(IClientSessionHandle session, IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
crs-indexer |          at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
crs-indexer |          at Blockcore.Indexer.Core.Storage.Mongo.BlockRewindOperation.MergeRewindInputsToUnspentTransactionsAsync(IMongoDb storage, Int64 blockIndex) in /home/runner/work/blockcore-indexer/blockcore-indexer/src/Blockcore.Indexer.Core/Storage/Mongo/BlockRewindOperation.cs:line 133
crs-indexer |          at Blockcore.Indexer.Core.Storage.Mongo.BlockRewindOperation.RewindBlockAsync(UInt32 blockIndex) in /home/runner/work/blockcore-indexer/blockcore-indexer/src/Blockcore.Indexer.Core/Storage/Mongo/BlockRewindOperation.cs:line 51
crs-indexer |          at Blockcore.Indexer.Cirrus.Storage.Mongo.CirrusBlockRewindOperation.RewindBlockAsync(UInt32 blockIndex) in /home/runner/work/blockcore-indexer/blockcore-indexer/src/Blockcore.Indexer.Cirrus/Storage/Mongo/CirrusBlockRewindOperation.cs:line 15
crs-indexer |          at Blockcore.Indexer.Core.Storage.Mongo.MongoData.DeleteBlockAsync(String blockHash) in /home/runner/work/blockcore-indexer/blockcore-indexer/src/Blockcore.Indexer.Core/Storage/Mongo/MongoData.cs:line 987
crs-indexer |          at Blockcore.Indexer.Core.Sync.SyncOperations.RewindToLastCompletedBlockAsync() in /home/runner/work/blockcore-indexer/blockcore-indexer/src/Blockcore.Indexer.Core/Sync/SyncOperations.cs:line 144
crs-indexer |          at Blockcore.Indexer.Core.Sync.SyncTasks.BlockStartup.OnExecute() in /home/runner/work/blockcore-indexer/blockcore-indexer/src/Blockcore.Indexer.Core/Sync/SyncTasks/BlockStartup.cs:line 78
crs-indexer |          at Blockcore.Indexer.Core.Sync.SyncTasks.TaskStarter.<>c__DisplayClass8_0.<<Run>b__0>d.MoveNext() in /home/runner/work/blockcore-indexer/blockcore-indexer/src/Blockcore.Indexer.Core/Sync/SyncTasks/TaskStarter.cs:line 37
```

**Comment by DavidGershony** [comment]
Which version of the indexer is running?

**Comment by dangershony** [comment]
I think it was 0.2.35
