### ISSUE TITLE
Sync stopped with InvalidBlockFound exception

### ISSUE THREAD

**Issue by sondreb** [block-core/blockcore-indexer#17]
The Stratis instance of the indexer stopped working:

```
fail: Blockcore.Indexer.Sync.SyncTasks.BlockStore[0]
      TaskRunner-BlockStore
Blockcore.Indexer.Sync.SyncRestartException: Exception of type 'Blockcore.Indexer.Sync.SyncRestartException' was thrown.
   at Blockcore.Indexer.Storage.Mongo.MongoStorageOperations.InvalidBlockFound(SyncBlockInfo lastBlock, SyncBlockTransactionsOperation item) in /home/runner/work/blockcore-indexer/blockcore-indexer/src/Blockcore.Indexer/Storage/Mongo/MongoStorageOperations.cs:line 300
   at Blockcore.Indexer.Sync.SyncTasks.BlockStore.OnExecute() in /home/runner/work/blockcore-indexer/blockcore-indexer/src/Blockcore.Indexer/Sync/SyncTasks/BlockStore.cs:line 76
   at Blockcore.Indexer.Sync.SyncTasks.TaskRunner.<>cDisplayClass14_0.<<Run>b0>d.MoveNext() in /home/runner/work/blockcore-indexer/blockcore-indexer/src/Blockcore.Indexer/Sync/SyncTasks/TaskRunner.cs:line 41
```

Last block: 1784302
Not synced: 1784303

Don't know if this is the block that fails or not.

![image](https://user-images.githubusercontent.com/309938/82872097-d8a38e00-9f32-11ea-97ca-f738c922fa5a.png)

**Comment by sondreb** [comment]
More log info:

```
info: Blockcore.Indexer.Sync.SyncServer[0]
      Sync: ### - Restart requested - ###
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      => ConnectionId:0HLVO4P84MQ0B => RequestPath:/api/query/block RequestId:0HLVO4P84MQ0B:00000001, SpanId:|703b20f6-4563e0a39d5ca93f., TraceId:703b20f6-4563e0a39d5ca93f, ParentId:
      An unhandled exception has occurred while executing the request.
MongoDB.Driver.MongoConnectionException: An exception occurred while receiving a message from the server.
 ---> System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at MongoDB.Driver.Core.Misc.StreamExtensionMethods.ReadBytes(Stream stream, Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Connections.BinaryConnection.ReceiveBuffer()
   --- End of inner exception stack trace ---
   at MongoDB.Driver.Core.Connections.BinaryConnection.ReceiveBuffer()
   at MongoDB.Driver.Core.Connections.BinaryConnection.ReceiveBuffer(Int32 responseTo, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Connections.BinaryConnection.ReceiveMessage(Int32 responseTo, IMessageEncoderSelector encoderSelector, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.ConnectionPools.ExclusiveConnectionPool.AcquiredConnection.ReceiveMessage(Int32 responseTo, IMessageEncoderSelector encoderSelector, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.ExecuteProtocol[TResult](IWireProtocol`1 protocol, ICoreSession session, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.Command[TResult](ICoreSession session, ReadPreference readPreference, DatabaseNamespace databaseNamespace, BsonDocument command, IEnumerable`1 commandPayloads, IElementNameValidator commandValidator, BsonDocument additionalOptions, Action`1 postWriteAction, CommandResponseHandling responseHandling, IBsonSerializer`1 resultSerializer, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.CommandOperationBase`1.ExecuteProtocol(IChannelHandle channel, ICoreSessionHandle session, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.ReadCommandOperation`1.ExecuteAttempt(RetryableReadContext context, Int32 attempt, Nullable`1 transactionNumber, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.RetryableReadOperationExecutor.Execute[TResult](IRetryableReadOperation`1 operation, RetryableReadContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.ReadCommandOperation`1.Execute(RetryableReadContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.AggregateOperation`1.Execute(RetryableReadContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.AggregateOperation`1.Execute(IReadBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.CountDocumentsOperation.Execute(IReadBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.ExecuteReadOperation[TResult](IReadBinding binding, IReadOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.ExecuteReadOperation[TResult](IClientSessionHandle session, IReadOperation`1 operation, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.ExecuteReadOperation[TResult](IClientSessionHandle session, IReadOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.CountDocuments(IClientSessionHandle session, FilterDefinition`1 filter, CountOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSession[TResult](Func`2 func, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.CountDocuments(FilterDefinition`1 filter, CountOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.FindFluent`2.CountDocuments(CancellationToken cancellationToken)
   at Blockcore.Indexer.Storage.Mongo.MongoData.Blocks(Int32 offset, Int32 limit) in /home/runner/work/blockcore-indexer/blockcore-indexer/src/Blockcore.Indexer/Storage/Mongo/MongoData.cs:line 199
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
fail: Blockcore.Indexer.Sync.SyncTasks.BlockStore[0]
      TaskRunner-BlockStore
Blockcore.Indexer.Sync.SyncRestartException: Exception of type 'Blockcore.Indexer.Sync.SyncRestartException' was thrown.
   at Blockcore.Indexer.Storage.Mongo.MongoStorageOperations.InvalidBlockFound(SyncBlockInfo lastBlock, SyncBlockTransactionsOperation item) in /home/runner/work/blockcore-indexer/blockcore-indexer/src/Blockcore.Indexer/Storage/Mongo/MongoStorageOperations.cs:line 300
   at Blockcore.Indexer.Sync.SyncTasks.BlockStore.OnExecute() in /home/runner/work/blockcore-indexer/blockcore-indexer/src/Blockcore.Indexer/Sync/SyncTasks/BlockStore.cs:line 76
   at Blockcore.Indexer.Sync.SyncTasks.TaskRunner.<>c__DisplayClass14_0.<<Run>b__0>d.MoveNext() in /home/runner/work/blockcore-indexer/blockcore-indexer/src/Blockcore.Indexer/Sync/SyncTasks/TaskRunner.cs:line 41
```

**Comment by dangershony** [comment]
I suppose we can close this?

**Comment by dangershony** [comment]
Code has changed if there is an issue we need to open a new bug
