### ISSUE TITLE
syscoin block explorer?

### ISSUE THREAD

**Issue by SIKOo971** [block-core/blockcore-indexer#185]
Hello @sondreb @dangershony Brothers. Can we able to create syscoin block explorer?

**Comment by sondreb** [comment]
We're only supporting Bitcoin-based blockchains. If anyone want to add support and maintain support for other type of blockchains, we'd be more than happy to review and accept pull requests.

**Comment by SIKOo971** [comment]
I understand, but for me now! im stuck with this page https://www.blockcore.net/create-chain

**Comment by SIKOo971** [comment]
I have Cointype, 
SCRIPT_ADDRESS = 0x5
PUBLIC_KEY_ADDRESS = 0x3f
SEGWIT_ADDRESS = sys

Just Trying to understand what other things i need to create, even how i add this config to indexer command like **dotnet run --chain=SYS**

**Comment by SIKOo971** [comment]
@sondreb will you help me with configuration. i will try to maintained on my VPS

**Comment by dangershony** [comment]
Ah its a blockcore based coin you are making? are you planning to merge this to the blockcore repo? to have blockcore run an indexer for you it must be merged to our repo.

> Just Trying to understand what other things i need to create, even how i add this config to indexer command like dotnet run --chain=SYS

It won't work that way, if you run it yourself you need to override the configuration file in app.settings

**Comment by dangershony** [comment]
I would suggest you submit a PR to blockcore so we can review what you did

**Comment by SIKOo971** [comment]
@dangershony yes it is blockchain based coin.
https://coinmarketcap.com/currencies/syscoin/

so how i am locally do this?

**Comment by SIKOo971** [comment]
i am new learner here, dont know how to put pr

**Comment by SIKOo971** [comment]
For example. tried to change --Chain=BTC Settings. how i can do locally?

**Comment by dangershony** [comment]
Ah syscoin is an existing blockchain and it seems to be utxo based right?  
https://github.com/syscoin/syscoin  

It should be possible to create a fullnode for it on blockcore however you can probably also just run a syscoin node and use our explorer. it will be easiest if yo find a syscoin docker hub node and just reference that in the indexer deployment scripts

**Comment by dangershony** [comment]
or you can create your own docker image here
https://github.com/syscoin/docker-syscoind

**Comment by dangershony** [comment]
> [Syscoin](https://medium.com/u/5431342d720?source=post_page-----3ff690a7ef5f--------------------------------)
 is the only dual chain UTXO / EVM architecture where all of the following characteristics are working in perfect harmony to comprise the layer 1 protocol.

Seems its like Cirrus the stratis sidechain a UTXO and smart contract meshed together.

**Comment by SIKOo971** [comment]
Ok i understand, i created syscoind. but how i use --chain=syc

**Comment by SIKOo971** [comment]
can you add sys in your blockcore list. so it will be easy for me. because i tried to use custom_btc. but its giving me error.

```
fail: Blockcore.Indexer.Core.Sync.SyncServer[0]
      Sync
      System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Array size too big')
         at NBitcoin.BitcoinStream.ReadWriteArray[T](T[]& data)
         at NBitcoin.BitcoinStream.ReadWriteList[TList,TItem](TList& data)
         at NBitcoin.BitcoinStream.ReadWrite[TList,TItem](TList& list)
         at Blockcore.Consensus.BlockInfo.PosTransaction.ReadWrite(BitcoinStream stream)
         at NBitcoin.BitcoinStream.ReadWrite[T](T& data)
         at NBitcoin.BitcoinStream.ReadWriteArray[T](T[]& data)
         at NBitcoin.BitcoinStream.ReadWriteList[TList,TItem](TList& data)
         at NBitcoin.BitcoinStream.ReadWrite[T](List`1& list)
         at Blockcore.Consensus.BlockInfo.Block.ReadWrite(BitcoinStream stream)
         at Blockcore.Consensus.BlockInfo.PosBlock.ReadWrite(BitcoinStream stream)
         at NBitcoin.BitcoinSerializableExtensions.ReadWrite(IBitcoinSerializable serializable, Byte[] bytes, ConsensusFactory consensusFactory)
         at Blockcore.Consensus.BlockInfo.Block.Parse(String hex, ConsensusFactory consensusFactory)
         at Blockcore.Indexer.Core.Sync.SyncOperations.SyncBlockInternal(SyncConnection connection, BlockInfo block) in C:\Users\CRSTUDIO\Downloads\blockcore-indexer-master\blockcore-indexer-master\src\Blockcore.Indexer.Core\Sync\SyncOperations.cs:line 239
         at Blockcore.Indexer.Core.Sync.SyncOperations.FetchFullBlock(SyncConnection connection, BlockInfo block) in C:\Users\CRSTUDIO\Downloads\blockcore-indexer-master\blockcore-indexer-master\src\Blockcore.Indexer.Core\Sync\SyncOperations.cs:line 105
         at Blockcore.Indexer.Core.Sync.SyncTasks.BlockPuller.FetchBlockAsync(Int64 tip) in C:\Users\CRSTUDIO\Downloads\blockcore-indexer-master\blockcore-indexer-master\src\Blockcore.Indexer.Core\Sync\SyncTasks\BlockPuller.cs:line 192
```

**Comment by dangershony** [comment]
You need to go to this files and make changes there
https://github.com/block-core/blockcore-indexer/blob/master/src/Blockcore.Indexer/appsettings.json#L20
https://github.com/block-core/blockcore-indexer/blob/master/src/Blockcore.Indexer/CUSTOM.json

But this is not gonna be so easy because it depends if a syscoin transactions can be serialized with one of our consensus serializers 

> can you add sys in your blockcore list. so it will be easy for me.   

I suppose we can try if I find the time but it might be a big job for a dev to do that

**Comment by SIKOo971** [comment]
I will wait, if you can make syscoin indexer. i will see my self too.. but waiting from your side

**Comment by dangershony** [comment]
ok if I find time soon I will try to do it

**Comment by SIKOo971** [comment]
sure thank bro @dangershony <3

**Comment by SIKOo971** [comment]
Hello Brother, @dangershony how are you, is there anything done?

**Comment by dangershony** [comment]
Not yet no, perhaps join our discord and maybe others in the community can help?

**Comment by SIKOo971** [comment]
@dangershony I Followed your instructions. and i finally created just changes done in custom.json and it works :) Thanks brother @dangershony

**Comment by SIKOo971** [comment]
@dangershony Brother, how can we stop sync and RPC connection? and just use the indexer without sync

**Comment by SIKOo971** [comment]
@dangershony @sondreb Hello Brothers, how are you. guys please help me, i tried to create RVN and my indexer stop sync http://74.208.160.105:9910/ in 1218326 height. and giving me error.

<a href="https://ibb.co/JQ1vgZH"><img src="https://i.ibb.co/JQ1vgZH/New.png" alt="New" border="0"></a>

**Comment by dangershony** [comment]
This most likely means you are using the wrong consensus factory, the code serializer is failing because there fields it's not expecting.

Is RGN a POD network? Do you need to use a POS consensus factory?

**Comment by SIKOo971** [comment]
RVN Is PoW Network. what should i have to do?

**Comment by dangershony** [comment]
You have to find out what are the different fileds that get serialized.

In your indexer settings file what did you set as the consensus factory type?

**Comment by SIKOo971** [comment]
i used custom.json and just change the symbol and RPC credentials.

**Comment by dangershony** [comment]
Ok so on the custom I suppose you left this part as is?
https://github.com/block-core/blockcore-indexer/blob/master/src/Blockcore.Indexer/CUSTOM.json#L12

Here you probably need to change the factory type to POW, can you try 
`  "NetworkConsensusFactoryType": "Blockcore.Consensus.BlockInfo.ConsensusFactory, Blockcore",`

**Comment by SIKOo971** [comment]
Check This Error After Changing NetworkConsensusFactoryType

<a href="https://ibb.co/Y00c50m"><img src="https://i.ibb.co/NTT90T5/Capture.jpg" alt="Capture" border="0"></a>

**Comment by dangershony** [comment]
Sorry try this line

`"NetworkConsensusFactoryType": "Blockcore.Consensus.ConsensusFactory, Blockcore"`

**Comment by SIKOo971** [comment]
fail: Blockcore.Indexer.Core.Sync.SyncServer[0]
      Sync
      System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Array size not big')
         at NBitcoin.Protocol.VarString.ReadWrite(BitcoinStream stream)
         at NBitcoin.BitcoinStream.ReadWrite(Script data)
         at NBitcoin.BitcoinStream.ReadWrite(Script& script)
         at Blockcore.Consensus.TransactionInfo.TxIn.ReadWrite(BitcoinStream stream)
         at NBitcoin.BitcoinStream.ReadWrite[T](T& data)
         at NBitcoin.BitcoinStream.ReadWriteArray[T](T[]& data)
         at NBitcoin.BitcoinStream.ReadWriteList[TList,TItem](TList& data)
         at Blockcore.Consensus.TransactionInfo.Transaction.ReadWrite(BitcoinStream stream)
         at NBitcoin.BitcoinStream.ReadWrite[T](T& data)
         at NBitcoin.BitcoinStream.ReadWriteArray[T](T[]& data)
         at NBitcoin.BitcoinStream.ReadWriteList[TList,TItem](TList& data)
         at Blockcore.Consensus.BlockInfo.Block.ReadWrite(BitcoinStream stream)
         at NBitcoin.BitcoinSerializableExtensions.ReadWrite(IBitcoinSerializable serializable, Byte[] bytes, ConsensusFactory consensusFactory)
         at Blockcore.Consensus.BlockInfo.Block.Parse(String hex, ConsensusFactory consensusFactory)
         at Blockcore.Indexer.Core.Sync.SyncOperations.SyncBlockInternal(SyncConnection connection, BlockInfo block) in /root/blockcore-indexer/src/Blockcore.Indexer.Core/Sync/SyncOperations.cs:line 239
         at Blockcore.Indexer.Core.Sync.SyncOperations.FetchFullBlock(SyncConnection connection, BlockInfo block) in /root/blockcore-indexer/src/Blockcore.Indexer.Core/Sync/SyncOperations.cs:line 105
         at Blockcore.Indexer.Core.Sync.SyncTasks.BlockPuller.FetchBlockAsync(Int64 tip) in /root/blockcore-indexer/src/Blockcore.Indexer.Core/Sync/SyncTasks/BlockPuller.cs:line 192


Still Same Error.

**Comment by dangershony** [comment]
That's a different error see when it tries to serialize the script
`NBitcoin.BitcoinStream.ReadWrite(Script data)`

 I think its serialization so it means the blocks for this network don't serialize the same.
Is this network implemented in C#  somewhere like NBitcoin?

**Comment by SIKOo971** [comment]
Dont Know brother, everything fine. just stuck in sync.

**Comment by SIKOo971** [comment]
CAN I TRY TO RESYNC? AND for example if i dont want to sync. how can i use indexer without network and sync standalone?

**Comment by SIKOo971** [comment]
> You will need to implement a consensus factory, not so easy but possible.
> 
> > how can i use indexer without network and sync standalone?
> 
> I am not sure I understand. What is RVN github?

How to implement?

**Comment by SIKOo971** [comment]
I want to know, for example my indexer stuck right now, how can i stop sync & rpc connections. and just query locally addresses

**Comment by SIKOo971** [comment]
http://74.208.160.105:9910/
I start resync with this settings
"NetworkConsensusFactoryType": "Blockcore.Consensus.ConsensusFactory, Blockcore"

let see what gonna happen

**Comment by dangershony** [comment]
You can access the swagger in this url http://74.208.160.105:9910/docs/index.html

**Comment by dangershony** [comment]
> Its Didnt Work, Just Browser Hang Round Round,   

This can be because it did not run indexes, it does that at the end.

> is there any possible way to open indexer and api runs without sync and rpc   

Once the sync is complete yo can stop the node and just use indexer and mongodb yes but you need it to finish so it will run indexes

**Comment by SIKOo971** [comment]
oh ok. http://74.208.160.105:9910/ check @dangershony brother rightnow its syncing hopefully everything works find. or else i will ask you later.

**Comment by SIKOo971** [comment]
> to implement a consensus factory

@dangershony 
Brother Will you help me to implement a consensus factory, for ravencoin.

**Comment by dangershony** [comment]
Hi mate, this might be a big task.
Can you perhaps try to find out how ravencoin differs from bitcoin, what fields are different?
It will be easier to know then how much work it will be
Is ravencoin implemented in NBitcoin?

**Comment by SIKOo971** [comment]
NBitcoin?

**Comment by SIKOo971** [comment]
@dangershony @sondreb Brothers I tried to implement a consensus factory, for raven coin. but i couldn't understand exactly. will you please help me out.

**Comment by SIKOo971** [comment]
I Tried https://github.com/team-exor/eiquidus, But there sync in MongoDB is very slow.

**Comment by dangershony** [comment]
Can you share the code?

**Comment by SIKOo971** [comment]
Sorry brother dont have the code, actually my co-friend developer tried and reinstall operating system. now my all hopes is you @dangershony

**Comment by SIKOo971** [comment]
Hello @dangershony Is there any hope?

**Comment by dangershony** [comment]
I am pretty busy and I think this task will take a good few days (have to understand how syscoin works) so not in the next few weeks

**Comment by SIKOo971** [comment]
> I am pretty busy and I think this task will take a good few days (have to understand how syscoin works) so not in the next few weeks

Brother Its Revcoin. Not Syscoin! Syscoin Works Fine.

**Comment by SIKOo971** [comment]
@dangershony RAVENCOIN GIVE ME THIS 

fail: Blockcore.Indexer.Core.Sync.SyncTasks.BlockPuller[0]
      TaskRunner-BlockPuller
      System.AggregateException: One or more errors occurred. (Specified argument was out of the range of valid values. (Parameter 'Array size not big'))
       ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Array size not big')
         at NBitcoin.Protocol.VarString.ReadWrite(BitcoinStream stream)
         at NBitcoin.BitcoinStream.ReadWrite(Script data)
         at NBitcoin.BitcoinStream.ReadWrite(Script& script)
         at Blockcore.Consensus.TransactionInfo.TxIn.ReadWrite(BitcoinStream stream)
         at NBitcoin.BitcoinStream.ReadWrite[T](T& data)
         at NBitcoin.BitcoinStream.ReadWriteArray[T](T[]& data)
         at NBitcoin.BitcoinStream.ReadWriteList[TList,TItem](TList& data)
         at Blockcore.Consensus.TransactionInfo.Transaction.ReadWrite(BitcoinStream stream)
         at NBitcoin.BitcoinStream.ReadWrite[T](T& data)
         at NBitcoin.BitcoinStream.ReadWriteArray[T](T[]& data)
         at NBitcoin.BitcoinStream.ReadWriteList[TList,TItem](TList& data)
         at Blockcore.Consensus.BlockInfo.Block.ReadWrite(BitcoinStream stream)
         at NBitcoin.BitcoinSerializableExtensions.ReadWrite(IBitcoinSerializable serializable, Byte[] bytes, ConsensusFactory consensusFactory)
         at Blockcore.Consensus.BlockInfo.Block.Parse(String hex, ConsensusFactory consensusFactory)
         at Blockcore.Indexer.Core.Sync.SyncOperations.SyncBlockInternal(SyncConnection connection, BlockInfo block) in /root/blockcore-indexer/src/Blockcore.Indexer.Core/Sync/SyncOperations.cs:line 239
         at Blockcore.Indexer.Core.Sync.SyncOperations.FetchFullBlock(SyncConnection connection, BlockInfo block) in /root/blockcore-indexer/src/Blockcore.Indexer.Core/Sync/SyncOperations.cs:line 105
         at Blockcore.Indexer.Core.Sync.SyncTasks.BlockPuller.FetchBlockAsync(Int64 tip) in /root/blockcore-indexer/src/Blockcore.Indexer.Core/Sync/SyncTasks/BlockPuller.cs:line 192
         --- End of inner exception stack trace ---
         at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
         at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
         at Blockcore.Indexer.Core.Sync.SyncTasks.BlockPuller.OnExecute() in /root/blockcore-indexer/src/Blockcore.Indexer.Core/Sync/SyncTasks/BlockPuller.cs:line 134

**Comment by dangershony** [comment]
This is a serialisation error.
I am intrigued now...
Let me try to look at this, maybe tomorrow.

**Comment by SIKOo971** [comment]
ok brother i will wait. thank you @dangershony

**Comment by SIKOo971** [comment]
@dangershony Hello Brother, How are you! Have you tried? 5 days back you said to me you will try that day. is there any news?

**Comment by dangershony** [comment]
No sorry my time is limited, can you share a TRX byte code that was used to get that serialization error?
Can you also share the repo where this coins is used?

**Comment by sondreb** [comment]
The Indexer software parses Blocks and Transactions and if those are in any shape or form different than Bitcoin, then modifications must be done to the indexer software. That's what the consensus factory is used for.

To add support for custom blockchains that are based off Bitcoin, but has been modified, then specification for the Block and/or Transaction format must be known and code modified.

Normally developers from different blockchain teams will provide that development support.
