### ISSUE TITLE
Bug: Indexer stops running with error: KeyNotFoundException: The given key '1f28f2671019e39f2d0d196abbf3c66db5e8d167329eccd2283ef9023b9918ae-0' was not present in the dictionary.

### ISSUE THREAD

**Issue by sondreb** [block-core/blockcore-indexer#80]
This error makes the indexer stop indexing new blocks:

```
fail: Blockcore.Indexer.Core.Sync.SyncTasks.BlockStore[0]
      TaskRunner-BlockStore
      System.Collections.Generic.KeyNotFoundException: The given key '1f28f2671019e39f2d0d196abbf3c66db5e8d167329eccd2283ef9023b9918ae-0' was not present in the dictionary.
         at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
         at Blockcore.Indexer.Core.Storage.Mongo.MongoStorageOperations.PushStorageBatch(StorageBatch storageBatch) in C:\src\github\blockcore\blockcore-indexer\src\Blockcore.Indexer.Core\Storage\Mongo\MongoStorageOperations.cs:line 164
         at Blockcore.Indexer.Core.Sync.SyncTasks.BlockStore.OnExecute() in C:\src\github\blockcore\blockcore-indexer\src\Blockcore.Indexer.Core\Sync\SyncTasks\BlockStore.cs:line 87
         at Blockcore.Indexer.Core.Sync.SyncTasks.TaskRunner.<>c__DisplayClass14_0.<<Run>b__0>d.MoveNext() in C:\src\github\blockcore\blockcore-indexer\src\Blockcore.Indexer.Core\Sync\SyncTasks\TaskRunner.cs:line 41
fail: Blockcore.Indexer.Core.Sync.SyncServer[0]
      Sync
      System.Collections.Generic.KeyNotFoundException: The given key '1f28f2671019e39f2d0d196abbf3c66db5e8d167329eccd2283ef9023b9918ae-0' was not present in the dictionary.
         at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
         at Blockcore.Indexer.Core.Storage.Mongo.MongoStorageOperations.PushStorageBatch(StorageBatch storageBatch) in C:\src\github\blockcore\blockcore-indexer\src\Blockcore.Indexer.Core\Storage\Mongo\MongoStorageOperations.cs:line 164
         at Blockcore.Indexer.Core.Sync.SyncTasks.BlockStore.OnExecute() in C:\src\github\blockcore\blockcore-indexer\src\Blockcore.Indexer.Core\Sync\SyncTasks\BlockStore.cs:line 87
         at Blockcore.Indexer.Core.Sync.SyncTasks.TaskRunner.<>c__DisplayClass14_0.<<Run>b__0>d.MoveNext() in C:\src\github\blockcore\blockcore-indexer\src\Blockcore.Indexer.Core\Sync\SyncTasks\TaskRunner.cs:line 41
      --- End of stack trace from previous location ---
         at Blockcore.Indexer.Core.Sync.SyncTasks.Runner.<>c__DisplayClass8_0.<<RunAll>b__2>d.MoveNext() in 
```

**Comment by DavidGershony** [comment]
The bug was fixed in PR https://github.com/block-core/blockcore-indexer/pull/82
